#!/bin/sh

source common.sh

init_tasklog

usage ()
{
    echo "Usage: "`basename $0`" [OPTIONS] <create|list>"
    exit 127
}

function=usage

case "$1" in
	"create")
		function=create_action
		shift
		;;
	"list")
		function=list_action
		shift
		;;
esac

$function $@

