#!/bin/sh
# Copyright (c) 2009 Matthieu Gautier <mgautier at fedoraproject dot org>

source common.sh

init_tasklog

usage ()
{
    echo "Usage: "`basename $0`" [OPTIONS] <task|action>"
    exit 127
}

function=usage

case "$1" in
	"task")
		function=list_task
		shift
		;;
	"action")
		function=list_action
		shift
		;;
esac

$function $@
