#!/bin/sh
# Copyright (c) 2009 Matthieu Gautier <mgautier at fedoraproject dot org>

source common.sh

init_tasklog

usage ()
{
    echo "Usage: "`basename $0`" [OPTIONS] <task|action>"
    echo "Options are:"
    echo "    -h        show help"
    echo "    -v        verbosity"
    echo "    -m        use merge strategy instead of rebasing"
    echo "    -cn       do not update the cvs repository"
    echo "    -V        show version information"
    echo
    exit 127
}

function=usage

case "$1" in
	"task")
		function=list_task
		shift
		;;
	"action")
		function=list_action
		shift
		;;
esac

$function $@
