#!/bin/sh

source common.sh

init_tasklog

usage ()
{
    echo "Usage: "`basename $0`" [OPTIONS] <create|list|close>"
    exit 127
}

function=usage

case "$1" in
	"create")
		function=create_task
		shift
		;;
	"list")
		function=list_task
		shift
		;;
	"close")
		function=close_task
		shift
		;;
esac

$function $@

